### ISSUE TITLE
Warning: line 7: unknown attribute 'keepoldvectorfont' in tag <setting>

### ISSUE THREAD

**Issue by kapilsinghrawat** [NordicSemiconductor/nrf5-eagle-reference-design#7]
Hi 
I'm using eagle 5.6 Version. 
While adding component I'm getting below warning  

[Warning.txt](https://github.com/NordicPlayground/nrf5-eagle-reference-design/files/2543920/Warning.txt)

Could you please check this issue.

**Comment by Cable89** [comment]
It seems this is a compatibility issue as the library was last saved from version 8.3.0.
If you are not using the newest parts, you could try checking out an earlier version of this repo.
Or since it is just a warning you could ignore it. From the name of the warning it does not seem to be an issue, just a new tag used for backwards compatibility in newer versions.
